config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root "galleries#index"

  namespace :admin do
    resources :galleries do
      member do
        post :reorder
      end
    end
  end

  resources :galleries

  get "/about" => "galleries#about", :as => "about"
  #get "/contact" => "galleries#contact", :as => "contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :attachments, class_name: "GalleryAttachment", dependent: :destroy, inverse_of: :gallery
  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank
  include RankedModel
  ranks :row_order
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  validates_presence_of :title
  validates_uniqueness_of :title

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize.to_s
  end

  def slug_candidates
    [
      :title,
      [:title, :description]
    ]
  end
end

app/models/gallery_attachment.rb
class GalleryAttachment < ApplicationRecord
  mount_uploader :attachment, GalleryAttachmentUploader
  belongs_to :gallery
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < ApplicationController
  before_action :authenticate_user!
  layout "admin"

  def index
    @galleries = Gallery.rank(:row_order).all
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save!
      redirect_to admin_galleries_path
    else
      render :new
    end
  end

  def edit
    @gallery = Gallery.friendly.find(params[:id])
  end

  def update
    @gallery = Gallery.friendly.find(params[:id])

    if @gallery.update(gallery_params)
      redirect_to admin_galleries_path
    else
      render :edit
    end
  end

  def destroy
    @gallery = Gallery.friendly.find(params[:id])

    @gallery.destroy

    redirect_to admin_galleries_path
  end

  def reorder
    @gallery = Gallery.friendly.find(params[:id])
    @gallery.row_order_position = params[:position]
    @gallery.save!


    respond_to do |format|
      format.html { redirect_to admin_galleries_path }
      format.json { render :json => { :message => "ok" }}
    end
  end

  private

  def gallery_params
    params.require(:gallery).permit(:title, :description, :image, :is_hidden, :show_text, :detail_description, attachments_attributes: [:id, :attachment, :_destroy])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    admin_galleries_path
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def index
    @galleries = Gallery.where(is_hidden: false).rank(:row_order).all

    set_page_image "https://dorislin.me/img/about.jpg"
  end

  def show
    @gallery = Gallery.friendly.find(params[:id])

    set_page_title @gallery.title
    set_page_description @gallery.detail_description
    set_page_image "https://dorislin.me#{@gallery.image.url}"
  end

  def about
    set_page_title "About - 關於我"
    set_page_image "https://dorislin.me/img/about.jpg"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if ((User.count == 2) & (user_signed_in?))
      redirect_to root_path
    elsif User.count == 2
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_hover_text(gallery)
    if gallery.show_text == true
      "box-masonry-text"
    else
      "box-masonry-hover-text-header"
    end
  end

  def render_hover_icon(gallery)
    return "with-hover-icon" if gallery.show_text == true
  end
end

app/views/admin/galleries/_form.html.erb
<%= simple_form_for [:admin, @gallery] do |f| %>
  <%= f.input :title, label: "標題" %>
  <%= f.input :description, as: :text, label: "內文（顯示在外面）" %>
  <%= f.input :is_hidden, label: "隱藏作品" %>
  <%= f.input :show_text, label: "桌面版時顯示圖片下方文字" %>
  <%= f.input :detail_description, as: :ckeditor, label: "內頁說明" %>
  <%= f.input :image, as: :file %>
  <%= image_tag f.object.image.url, class: "img-responsive" if f.object.image.present? %>

<%= f.nested_fields_for :attachments do |ff| %>
  <fieldset style="border-left: 5px solid #bbb; margin-bottom: 10px; padding: 10px;">
    <legend>Attachment</legend>
    <div class="form-group">
      <%= ff.label :attachment %>
      <%= ff.file_field :attachment, :class => "form-control" %>
      <% if ff.object.attachment.present? %>
      已經上傳檔案 <%= image_tag ff.object.attachment.url, class: "img-responsive" %>
      <% end %>
    </div>
    <%= ff.remove_nested_fields_link "移除這個檔案", :class => "btn btn-danger" %>
  </fieldset>
<% end %>
<p class="text-left">
  <%= f.add_nested_fields_link :attachments, "新增內頁圖片", :class => "btn btn-default" %>
</p>

  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

<script>
  autosize($('#gallery_description'));
</script>

app/views/admin/galleries/edit.html.erb
<%= render "form" %>

app/views/admin/galleries/index.html.erb
<%= link_to "New", new_admin_gallery_path %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Image</th>
      <th>Title</th>
      <th>Description</th>
      <th>Setting</th>
    </tr>
  </thead>
    <tbody class="sortable">
      <% @galleries.each do |gallery| %>
        <tr data-reorder-url="<%= reorder_admin_gallery_path(gallery) %>">
          <td><span class="sortable_icon">☰</span></td>
          <td><%= image_tag gallery.image.thumb %></td>
          <td><%= gallery.title %></td>
          <td><%= gallery.description %></td>
          <td>
            <%= link_to "Edit", edit_admin_gallery_path(gallery) %>
            |
            <%= link_to "Destroy", admin_gallery_path(gallery), method: :delete, data: { confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>

<script>
$( ".sortable" ).sortable({
  axis: 'y',       // 限制只能上下拖拉
  items: 'tr',     // 拖拉整个 tr
  cursor: 'move',  // 变更拖拉时的 icon
  handle: ".sortable_icon",  // 限制只有点 ☰ 才能开始拖拉，砍掉这行的话，会是整个 tr 都可以进行拖拉，你可以试试看
  stop: function(e, ui){     // 当拖拉结束时，会调用这个方法
    ui.item.children('td').effect('highlight', {}, 1000)
  },
  update: function(e, ui) {   // 当拖拉结束并且 DOM 上的位置变更时，会调用这个方法
    reorder_url = ui.item.data('reorder-url')
    position = ui.item.index()  // 取得顺序
    $.ajax({
     type: 'POST',
     url: reorder_url,
     dataType: 'json',
     data: { position: position }
    })
  }
});
</script>

app/views/admin/galleries/new.html.erb
<%= render "form" %>

app/views/common/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-106013284-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/common/_side_bar.html.erb
<div id="sidebar" class="col-xs-6 col-sm-4 col-md-3 sidebar-offcanvas">
  <div class="sidebar-content">
    <h1 class="sidebar-heading"> <%= link_to "Doris Lin", root_path %></h1>
    <p class="sidebar-p"> 我是一名 UI 設計師，有一年以上的網站 UI 設計經驗，會手繪、電繪、平面設計，對於美感有自己的執著。 </p>
    <ul class="sidebar-menu">
      <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "作品集", root_path %></li>
      <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "關於我", about_path %></li>
    </ul>
    <p class="social">
      <a href="https://www.behance.net/doristaiwaa0be" data-animate-hover="pulse" class="external behance">
        <i class="fa fa-behance"></i>
      </a>

      <a href="mailto:doristaiwan12@gmail.com" data-animate-hover="pulse" class="email">
        <i class="fa fa-envelope"></i>
      </a>
    </p>
    <div class="copyright">
      <p class="credit">Copyright ©2017 Doris Lin <br>
    Design by <a href="https://www.linkedin.com/in/nic-lin/" target=_new>Nic Lin</a></p>
    </div>
  </div>
</div>

app/views/galleries/about.html.erb
<!--   *** DETAIL ***-->
<div class="row">
  <div class="col-lg-8">
    <div class="content-column-content">
      <h1>About Me</h1>
        <p class="lead">我的優勢</p>
        <p>1. 有五年以上的手繪經驗，具有優秀的佈局感和色彩感</p>
        <p>2. 有協作能力、樂於和同事們溝通並且討論</p>
        <p>3. 有新創團隊網頁平面設計經驗</p>
        <p>4. 對於 HTML5 CSS 有一定程度的瞭解</p>
        <p>5. 熟悉使用Photoshop、illustrator、AutoCAD、Sketchup及其主流設計類軟件</p>
      </p>
      <div class="row">
        <div class="col-md-4">
          <p>
            <%= image_tag "about.jpg", class: "image img-circle img-responsive" %>
          </p>
        </div>
        <div class="col-md-8">
          <div class="skill-item">
            <div class="progress-title">Photoshop</div>
            <div class="progress">
              <div role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 75%;" class="progress-bar progress-bar-skill1"><span class="sr-only">60</span></div>
            </div>
          </div>
          <div class="skill-item">
            <div class="progress-title">illustrator</div>
            <div class="progress">
              <div role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 73%;" class="progress-bar progress-bar-skill2"><span class="sr-only">70</span></div>
            </div>
          </div>
          <div class="skill-item">
            <div class="progress-title">Sketch</div>
            <div class="progress">
              <div role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 62%;" class="progress-bar progress-bar-skill4"><span class="sr-only">80</span></div>
            </div>
          </div>
          <div class="skill-item">
            <div class="progress-title">AutoCAD</div>
            <div class="progress">
              <div role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 76%;" class="progress-bar progress-bar-skill3"><span class="sr-only">90</span></div>
            </div>
          </div>
          <div class="skill-item">
            <div class="progress-title">3Dmax</div>
            <div class="progress">
              <div role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 73%;" class="progress-bar progress-bar-skill4"><span class="sr-only">100</span></div>
            </div>
          </div>
        </div>
      </div>
      <h4 class="text-uppercase">工作經歷</h4>
      <ul>
        <li>2016-2017 冠通網路科技公司 UI / 平面設計師</li>
      </ul>
      <p>負責<a href="https://travbe.com/">Travbe旅遊網站</a>風格及 UI 畫面設計，知名藝術家<a href="http://chiusm.com/">邱素美</a>個人網站設計訂製、博奕網站 UI 設計、Desktop Software icon 設計。</p>

      <h4 class="text-uppercase">教育經歷</h4>
      <ul>
        <li>2013-2017 中國科技大學 室內設計系</li>
      </ul>
    </div>
  </div>
</div>

app/views/galleries/contact.html.erb
<!--   *** DETAIL ***-->
<div class="row">
  <div class="col-lg-8">
    <div class="content-column-content">
      <h1>Get in touch</h1>
      <p class="lead">When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then</p>
      <p>Effects present letters inquiry no an removed or friends. Desire behind latter me though in. Supposing shameless am he engrossed up additions. My possible peculiar together to. Desire so better am cannot he up before points. Remember mistaken opinions it pleasure of debating. Court front maids forty if aware their at. Chicken use are pressed removed. </p>
      <p>Able an hope of body. Any nay shyness article matters own removal nothing his forming. Gay own additions education satisfied the perpetual. If he cause manor happy. Without farther she exposed saw man led. Along on happy could cease green oh. </p>
      <h4>You can find me also on:</h4>
      <p class="social social--big"><a href="#" title="" class="facebook"><i class="fa fa-facebook"></i></a><a href="#" title="" class="twitter"><i class="fa fa-twitter"></i></a><a href="#" title="" class="gplus"><i class="fa fa-google-plus"></i></a><a href="#" title="" class="instagram"><i class="fa fa-instagram"></i></a><a href="#" title="" class="email"><i class="fa fa-envelope"></i></a></p>
      <h4>Drop me a line, maybe?</h4>
      <p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline.</p>
      <form id="contact-form" method="post" action="#" class="contact-form form">
        <div class="controls">
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <label for="name">Your firstname *</label>
                <input type="text" name="name" id="name" required="required" class="form-control">
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <label for="surname">Your lastname *</label>
                <input type="text" name="surname" id="surname" required="required" class="form-control">
              </div>
            </div>
          </div>
          <div class="form-group">
            <label for="email">Your email *</label>
            <input type="email" name="email" id="email" required="required" class="form-control">
          </div>
          <div class="form-group">
            <label for="message">Your message for me *</label>
            <textarea rows="4" name="message" id="message" required="required" class="form-control"></textarea>
          </div>
          <div>
            <input type="submit" value="Send" class="btn btn-ghost">
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/galleries/index.html.erb
<div class="grid">
  <div class="row">
    <% @galleries.each do |gallery| %>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 masonry-item">
      <div class="box-masonry">
      <%= link_to gallery_path(gallery), class: "box-masonry-image with-hover-overlay #{render_hover_icon(gallery)}" do %>
          <%= image_tag gallery.image.medium, class: "img-responsive" if gallery.image.present? %>
      <% end %>
        <div class="<%= render_hover_text(gallery)%>">
          <h4> <%= link_to gallery.title, "#"%></h4>
          <div class="box-masonry-desription">
            <p> <%= gallery.description %> </p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/galleries/show.html.erb
<div class="row">
  <div class="col-lg-8">
    <div class="content-column-content">
      <h1><%= @gallery.title %></h1>
      <div id="main-slider">
        <% if @gallery.attachments.present? %>
          <% @gallery.attachments.each do |attachment| %>
          <div class="item">
            <%= image_tag attachment.attachment.url, class: "img-responsive" %>
          </div>
          <% end %>
          <% else %>
          <div class="item">
            <%= image_tag @gallery.image.medium, class: "img-responsive" %>
          </div>
        <% end %>
      </div>
      <%= sanitize(@gallery.detail_description) %>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dorislin</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <meta property="og:image" content="<%= page_image %>"/>
    <%= render_page_title_meta_tag %>
    <%= render_page_description_meta_tag %>
    <%= render_page_keywords_meta_tag %>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all' %>

    <%= yield :javascripts %>
  </head>
<body id="<%= "#{controller_name}-#{action_name}"%>" >
  <div class="top-control"">
    <% if user_signed_in? %>
      <%= link_to('進後台', admin_galleries_path, class: "top-control__link") %>
    <% end %>
  </div>
    <div id="all">
      <div class="container-fluid">
        <div class="row row-offcanvas row-offcanvas-left">
          <%= render "common/side_bar"%>
          <div class="col-xs-12 col-sm-8 col-md-9 content-column <%= "white-background" unless current_page?(root_path) %>">
            <div class="small-navbar visible-xs">
              <button type="button" data-toggle="offcanvas" class="btn btn-ghost pull-left"> <i class="fa fa-align-left"> </i>Menu</button>
              <h1 class="small-navbar-heading"> <%= link_to "Doris Lin", root_path %></h1>
            </div>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <%= javascript_include_tag 'admin', async: true %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render_page_title_tag %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <meta property="og:image" content="<%= page_image %>"/>
    <%= render_page_title_meta_tag %>
    <%= render_page_description_meta_tag %>
    <%= render_page_keywords_meta_tag %>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>

    <%= yield :javascripts %>
  </head>
<body id="<%= "#{controller_name}-#{action_name}"%>" >
  <div class="top-control"">
    <% if user_signed_in? %>
      <%= link_to('進後台', admin_galleries_path, class: "top-control__link") %>
    <% end %>
  </div>
    <div id="all">
      <div class="container-fluid">
        <div class="row row-offcanvas row-offcanvas-left">
          <%= render "common/side_bar"%>
          <div class="col-xs-12 col-sm-8 col-md-9 content-column <%= "white-background" unless current_page?(root_path) %>">
            <div class="small-navbar visible-xs">
              <button type="button" data-toggle="offcanvas" class="btn btn-ghost pull-left"> <i class="fa fa-align-left"> </i>Menu</button>
              <h1 class="small-navbar-heading"> <%= link_to "Doris Lin", root_path %></h1>
            </div>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <%= javascript_include_tag 'application', async: true %>
    <%= render "common/google_analytics" if Rails.env.production? %>
  </body>
</html>